version: '2'
services:
  likuidecf-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/likuidecf/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=likuidecf
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
